sudo: required
dist: trusty
language: node_js
node_js:
  - '8.9'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@5.5.1

install:
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install
  - npm run build-local-dev
# TODO: npm run build-prod instead

# travis auto-runs test... which times out
script:
  - ng test --watch=false
  - ng build-prod
